<a href="https://colab.research.google.com/github/rrenyxa/Gauss/blob/main/Gauss_mehod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
dim = random.randint(2,5)
print(dim)
a = np.random.randint(-100,100,size=(dim,dim + 1)).astype('float32')
print(a)
for column in range(dim):
  a[column,:] = a[column,:]/a[column,column]
print(a)

3
[[ 49. -70.  65.  57.]
 [ -3. -47.  98. -51.]
 [-86. -73. -28. -88.]]
[[ 1.         -1.4285715   1.3265306   1.1632653 ]
 [ 0.06382979  1.         -2.0851064   1.0851064 ]
 [ 3.0714285   2.607143    1.          3.142857  ]]


In [ ]:
def move_zero(a, row, column):
    if (a[row,column] == 0):
      a[:,[row,]]


  return a

In [ ]:
def triangle(a):
  for column in range(dim):
    a[column,:] = a[column,:]/a[column,column]
    for row in range(column + 1, dim):
      if(~(a[row,column] == 0)):
        a[row,:] = a[row,:] - a[row,:]*a[column,:]
  return(a)

In [ ]:
triangle(a)
print(a)


[[ 1.         -1.4285715   1.3265306   1.1632653 ]
 [ 0.          1.          0.2803504  -0.07294834]
 [-0.         -0.          1.          2.3428936 ]]


In [ ]:
def back_triangle(a):
  for column in reversed(range(1,dim)):
    a[0:column,-1] = a[0:column,-1] - a[column-1,column]*a[column,-1]
    a[0:column,column] = 0
  return a
    

In [ ]:
print(back_triangle(a))

[[ 1.         0.         0.        -0.5361079]
 [ 0.         1.         0.        -0.7297795]
 [-0.        -0.         1.         2.3428936]]


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[-1])

5
